// <auto-generated />
using System;
using EvoJiuJitsu.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvoJiuJitsu.Data.Migrations
{
    [DbContext(typeof(EvoDbcontext))]
    [Migration("20240408184754_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EvoJiuJitsu.Business.Models.Atleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaPeso")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaPorIdade")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Faixa")
                        .HasColumnType("int");

                    b.Property<string>("Idade")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<int>("Polo")
                        .HasColumnType("int");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("Varchar(100");

                    b.HasKey("Id");

                    b.ToTable("Atletas", (string)null);
                });

            modelBuilder.Entity("EvoJiuJitsu.Business.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("Varchar(100");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId")
                        .IsUnique();

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("EvoJiuJitsu.Business.Models.Endereco", b =>
                {
                    b.HasOne("EvoJiuJitsu.Business.Models.Atleta", "Atleta")
                        .WithOne("Endereco")
                        .HasForeignKey("EvoJiuJitsu.Business.Models.Endereco", "AtletaId")
                        .IsRequired();

                    b.Navigation("Atleta");
                });

            modelBuilder.Entity("EvoJiuJitsu.Business.Models.Atleta", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
